### ISSUE TITLE
Glances data fetching doesn't work

### ISSUE THREAD

**Issue by Steeven9** [erohtar/Dasherr#13]
I am encountering some problems with the glances widget:

- Omitting the slash at the end of the URL, no fetching at all is performed.
```
{
    "name": "caroline",
    "type": "glances",
    "settings": {
        "url": "http://192.168.178.38:61208",
        "refreshMs": 5000
    }
}
```
![image](https://user-images.githubusercontent.com/25285679/205530748-9a394419-3d29-42d7-a869-91f21b21a1f3.png)

- If you try fetching from a HTTP address, you get a `Blocked loading mixed active content from http://192.168.178.38:61208/api/3/quicklook` error
```
{
    "name": "caroline",
    "type": "glances",
    "settings": {
        "url": "http://192.168.178.38:61208/",
        "refreshMs": 5000
    }
}
```
![image](https://user-images.githubusercontent.com/25285679/205530698-6001e559-5218-417c-bed8-7f69fb952d2c.png)

- Changing the protocol to HTTPS, the error changes to `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://caroline:61208/api/3/quicklook. (Reason: CORS request did not succeed). Status code: (null).`
```
{
    "name": "caroline",
    "type": "glances",
    "settings": {
        "url": "https://192.168.178.38:61208/",
        "refreshMs": 5000
    }
}
```
![image](https://user-images.githubusercontent.com/25285679/205530609-0b39c51d-6eb7-4def-aa0e-f546b6641720.png)

Over on the glances console, on the other hand, I get this weird looking logs:
```
192.168.178.25 - - [05/Dec/2022 03:37:49] code 400, message Bad request version ('üp{@õKB\x8bKöÅ\x99õ?à¶\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
192.168.178.25 - - [05/Dec/2022 03:37:49] code 400, message Bad request version ('N³ºülÈ\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
```

Current setup: Dasherr v1.04.00 hosted on a Synology Web Station host (aka a glorified apache webserver), with HTTPS enabled. Testing on Firefox 107.0.1 (64-bit)

**Comment by erohtar** [comment]
I'm looking into this.

**Comment by erohtar** [comment]
BTW thank you for all these details! 
While I may not be able to recreate the exact problem on my end, I might have to ask you to test some beta changes for me if that's okay.

**Comment by Steeven9** [comment]
No problem! I'd be happy to help :)

**Comment by erohtar** [comment]
I see that you tried updating Glances path to HTTPS, but in that case are you also opening Dasherr on HTTPS? Or the other way round?

> What is Mixed Content?
> When a user visits a page served over HTTP, their connection is open for eavesdropping and man-in-the-middle (MITM) attacks. When a user visits a page served over HTTPS, their connection with the web server is authenticated and encrypted with SSL and hence safeguarded from eavesdroppers and MITM attacks.
> 
> However, if an HTTPS page includes HTTP content, the HTTP portion can be read or modified by attackers, even though the main page is served over HTTPS. When an HTTPS page has HTTP content, we call that content “mixed”. The webpage that the user is visiting is only partially encrypted, since some of the content is retrieved unencrypted over HTTP. The Mixed Content Blocker blocks certain HTTP requests on HTTPS pages.

Also, could you try:
> If you need to allow the mixed content to be displayed, you can do that easily:
> Click the shield icon Mixed Content Shield in the address bar and choose Disable Protection on This Page from the dropdown menu.
> The icon in the address bar will change to an orange warning triangle Warning Identity Icon to remind you that insecure content is being displayed.

**Comment by Steeven9** [comment]
> I see that you tried updating Glances path to HTTPS, but in that case are you also opening Dasherr on HTTPS? 

Yes, I am hosting Dasherr on a HTTPS webserver; I tried changing the glances links to HTTPS only so it wouldn't complain about mixed content, but I guess that will break since the servers don't have certificates set up.

> Click the shield icon Mixed Content Shield in the address bar and choose Disable Protection on This Page from the dropdown menu.

This works, but it resets each time the browser is restarted, so it's _really_ temporary, and I haven't found a way to persist it yet.

**Comment by erohtar** [comment]
I see. What about the rest of the items on your dashboard? Is it possible the mixed content warning is coming from the online check of some HTTP services?

**Comment by Steeven9** [comment]
Mmmh no, I can see from the URL that it does come from the glances checks. I suppose that - together with the CORS errors - it stems from the fact that Dasherr is running on the frontend instead of having a dedicated backend/container like, for example, Uptime Kuma.

**Comment by erohtar** [comment]
> Dasherr is running on the frontend instead of having a dedicated backend/container

That's actually very much intentional - All other dashboards with a dedicated backend would have a footprint on the resources of the server, while if you disable the single widget, once the page loads, there's absolutely zero impact on the server, no matter how many clients access it at a time. Yes there's the impact of the webserver, but in case user was already running running one, Dasherr could be added to a sub-folder there without causing any overhead.

I actually was too bothered by resources consumed by the Dashboards I've been using, so went on to create something very light - almost static with the absolute minimum of dynamicity.

But I do want to solve the problem you're facing. I tried to replace the API request to Glances with a javascript fetch() since it supports no-cors mode (that's what I use for online checks), but that causes Glances to return a blank response. 

Assuming you must have faced some https related issues with other services you're hosting, would you have any ideas as to what might make it work for you?

**Comment by erohtar** [comment]
Based on everything I've found on the subject, it seems you'd have to enable CORS on server side to allow Dasherr to access it. Another solution I found was to route requests via a proxy but that's inefficient.
You may or may not be open to it, but have you considered using something like Tailscale? That would make inter-connecting services immensely simpler for you while things would still work the same for outsiders.

**Comment by Steeven9** [comment]
I see. I'll try routing the requests via a reverse proxy and see if that does the trick. It shouldn't add a lot of overhead since everything is inside the network, plus iirc the Glances requests are non-blocking so it shouldn't impact the overall page loading time. Thanks for your help!

**Comment by erohtar** [comment]
Great, let me know how it goes - all the best!

**Comment by LeeThompson** [comment]
I'm still building my new intranet server and hadn't thought to try dashboard over https, yeah this breaks really badly.   (It's even worse because I'm using a temporary name for the server which isn't listen in the SAN part of the certificate.)

Host checks fail:
```
Uncaught (in promise) TypeError: Failed to fetch
    at checkOnline (worker.js:172:25)
    at window.onload (worker.js:60:4)
```

**Comment by erohtar** [comment]
@LeeThompson Sorry I've been really tied up and couldn't get to this sooner. So, if you're switching to https, you'll have to ensure EVERYTHING is running on https - that means all your services that Dasherr tries to access and Glances. 
I'd assume you'd have to get valid site certificates (letsencrypt can help) and each of the services that are being online checked are running on sub-domains . Otherwise, while Dasherr would load, it'd be blocked by Chrome for Mixed Content issues (like @Steeven9 mentioned above).

@Steeven9 Should I understand your issue is resolved and I can close this?

**Comment by LeeThompson** [comment]
So basically this is a browser limitation, understood.
I should be able to work around this.

**Comment by erohtar** [comment]
Great - I'll close this, but pls feel free to let me know in case there are further issues.
