### ISSUE TITLE
[Feature Request] Additional Section Features

### ISSUE THREAD

**Issue by LeeThompson** [erohtar/Dasherr#4]
It would be nice if Sections (or at least the title) could be fancied up with text decoration modes (all uppercase, etc), different colors, background colors, font faces.

It would also be nice to have the option to have sections fill out to the right instead of down.

**Comment by erohtar** [comment]
- All uppercase would be easy to do through the settings yourself:
![image](https://user-images.githubusercontent.com/5120628/201477486-b270c7a0-05c3-4f50-b857-3bd9b79cf3c8.png)
- Colors/Background options should be covered by the themes (I've kept the theming really simple on purpose so that me or anyone else can create more themes very easily and quickly)
- Sections to right? I'm not sure I follow - could you pls demonstrate with some picture? Also pls show how would that work on a mobile screen

**Comment by LeeThompson** [comment]
It would be tricky to do it to the right with the way the status indicators work but something like:

`MONITOR     (icon) Glances (status)   (icon) Healthchecks (status)   (icon) UptimeKuma (status)`

Might require moving the status dot between the icon and the title.

**Comment by erohtar** [comment]
I think that might look rather cluttered - also, it won't work well on a mobile screen (which right now IMO works very well)

**Comment by LeeThompson** [comment]
That would be a downside, I guess forget the direction option so I guess close this one.

**Comment by erohtar** [comment]
Glad you concur.
